# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ruifag/6502

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ruifag/6502

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruifag/6502/CMakeFiles /home/ruifag/6502//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruifag/6502/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfot_lib

# Build rule for target.
sfot_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfot_lib
.PHONY : sfot_lib

# fast build rule for target.
sfot_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/build
.PHONY : sfot_lib/fast

#=============================================================================
# Target rules for targets named sfot

# Build rule for target.
sfot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfot
.PHONY : sfot

# fast build rule for target.
sfot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot.dir/build.make CMakeFiles/sfot.dir/build
.PHONY : sfot/fast

#=============================================================================
# Target rules for targets named sfot-tests

# Build rule for target.
sfot-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfot-tests
.PHONY : sfot-tests

# fast build rule for target.
sfot-tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/sfot-tests.dir/build.make tests/CMakeFiles/sfot-tests.dir/build
.PHONY : sfot-tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/fsm.o: src/fsm.cpp.o
.PHONY : src/fsm.o

# target to build an object file
src/fsm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/fsm.cpp.o
.PHONY : src/fsm.cpp.o

src/fsm.i: src/fsm.cpp.i
.PHONY : src/fsm.i

# target to preprocess a source file
src/fsm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/fsm.cpp.i
.PHONY : src/fsm.cpp.i

src/fsm.s: src/fsm.cpp.s
.PHONY : src/fsm.s

# target to generate assembly for a file
src/fsm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/fsm.cpp.s
.PHONY : src/fsm.cpp.s

src/loader.o: src/loader.cpp.o
.PHONY : src/loader.o

# target to build an object file
src/loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/loader.cpp.o
.PHONY : src/loader.cpp.o

src/loader.i: src/loader.cpp.i
.PHONY : src/loader.i

# target to preprocess a source file
src/loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/loader.cpp.i
.PHONY : src/loader.cpp.i

src/loader.s: src/loader.cpp.s
.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/loader.cpp.s
.PHONY : src/loader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot.dir/build.make CMakeFiles/sfot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot.dir/build.make CMakeFiles/sfot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot.dir/build.make CMakeFiles/sfot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/memory.o: src/memory.cpp.o
.PHONY : src/memory.o

# target to build an object file
src/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/memory.cpp.o
.PHONY : src/memory.cpp.o

src/memory.i: src/memory.cpp.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/memory.cpp.i
.PHONY : src/memory.cpp.i

src/memory.s: src/memory.cpp.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/memory.cpp.s
.PHONY : src/memory.cpp.s

src/opcodes.o: src/opcodes.cpp.o
.PHONY : src/opcodes.o

# target to build an object file
src/opcodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/opcodes.cpp.o
.PHONY : src/opcodes.cpp.o

src/opcodes.i: src/opcodes.cpp.i
.PHONY : src/opcodes.i

# target to preprocess a source file
src/opcodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/opcodes.cpp.i
.PHONY : src/opcodes.cpp.i

src/opcodes.s: src/opcodes.cpp.s
.PHONY : src/opcodes.s

# target to generate assembly for a file
src/opcodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/opcodes.cpp.s
.PHONY : src/opcodes.cpp.s

src/sfot.o: src/sfot.cpp.o
.PHONY : src/sfot.o

# target to build an object file
src/sfot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/sfot.cpp.o
.PHONY : src/sfot.cpp.o

src/sfot.i: src/sfot.cpp.i
.PHONY : src/sfot.i

# target to preprocess a source file
src/sfot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/sfot.cpp.i
.PHONY : src/sfot.cpp.i

src/sfot.s: src/sfot.cpp.s
.PHONY : src/sfot.s

# target to generate assembly for a file
src/sfot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfot_lib.dir/build.make CMakeFiles/sfot_lib.dir/src/sfot.cpp.s
.PHONY : src/sfot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... sfot"
	@echo "... sfot-tests"
	@echo "... sfot_lib"
	@echo "... src/fsm.o"
	@echo "... src/fsm.i"
	@echo "... src/fsm.s"
	@echo "... src/loader.o"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/opcodes.o"
	@echo "... src/opcodes.i"
	@echo "... src/opcodes.s"
	@echo "... src/sfot.o"
	@echo "... src/sfot.i"
	@echo "... src/sfot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

